spring.datasource.url=jdbc:postgresql://localhost:5432/assetvaultdb
spring.datasource.username=assetvault_user
spring.datasource.password=assetvault_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.h2.console.enabled=false
logging.level.com.assetvault=INFO
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN
spring.sql.init.mode=never