spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/assetvaultdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:assetvault_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:assetvault_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.h2.console.enabled=false
logging.level.com.Gemini.AssetVault=INFO
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN
spring.sql.init.mode=never
spring.jpa.open-in-view=false
