spring.application.name=AssetVault
spring.profiles.default=dev
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html
spring.jackson.default-property-inclusion=non_null
spring.jpa.open-in-view=false
logging.level.root=INFO
logging.level.org.springframework=INFO