spring.application.name=AssetVault
spring.profiles.active=dev
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
springdoc.swagger-ui.path=/swagger-ui.html
spring.jackson.default-property-inclusion=non_null
jwt.secret=assetvault-super-secret-key-must-be-256-bits-long-for-hs256-algo
jwt.expiration.ms=86400000














